const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Behaviors.Bullet,
		C3.Plugins.Text,
		C3.Plugins.TextBox,
		C3.Plugins.Button,
		C3.Plugins.Browser,
		C3.Plugins.AJAX,
		C3.Plugins.Dictionary,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{chao: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{PlayerLocal: 0},
	{Touch: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{PlaterRemote: 0},
	{chao2: 0},
	{teleport_1: 0},
	{teleport_2: 0},
	{Bullet: 0},
	{bullet: 0},
	{fundo: 0},
	{fak: 0},
	{tituloDoJogo: 0},
	{nome: 0},
	{entrar: 0},
	{dicanome: 0},
	{codigo: 0},
	{dicacodigo: 0},
	{criarsala: 0},
	{ou: 0},
	{dicacriarsala: 0},
	{Browser: 0},
	{AJAX: 0},
	{NetPlayers: 0},
	{TxtStatus: 0},
	{wsUrl: 0},
	{roomId: 0},
	{playerId: 0},
	{nickname: 0},
	{isConnected: 0},
	{sendRateMs: 0},
	{sendTimer: 0}
];

self.InstanceType = {
	chao: class extends self.ISpriteInstance {},
	PlayerLocal: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	PlaterRemote: class extends self.ISpriteInstance {},
	chao2: class extends self.ISpriteInstance {},
	teleport_1: class extends self.ISpriteInstance {},
	teleport_2: class extends self.ISpriteInstance {},
	bullet: class extends self.ISpriteInstance {},
	fundo: class extends self.ISpriteInstance {},
	fak: class extends self.ISpriteInstance {},
	tituloDoJogo: class extends self.ITextInstance {},
	nome: class extends self.ITextInputInstance {},
	entrar: class extends self.IButtonInstance {},
	dicanome: class extends self.ITextInstance {},
	codigo: class extends self.ITextInputInstance {},
	dicacodigo: class extends self.ITextInstance {},
	criarsala: class extends self.IButtonInstance {},
	ou: class extends self.ITextInstance {},
	dicacriarsala: class extends self.ITextInstance {},
	Browser: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	NetPlayers: class extends self.IDictionaryInstance {},
	TxtStatus: class extends self.ITextInstance {}
}